# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:20-alpine AS builder

# Copy the entire project
COPY . /app
WORKDIR /app

# Use build cache for faster builds
RUN --mount=type=cache,target=/root/.npm npm ci

FROM node:20-alpine AS release

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

WORKDIR /app

RUN npm ci --ignore-scripts --omit=dev

ENTRYPOINT ["node", "dist/main/index.js"]
